# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitManager' do
 
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'RCTLinkingIOS',
  ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end